name: SBGitActBDMySQL

on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      # Запускаем MySQL как сервис, который будет доступен для тестов
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Vad310865!
          MYSQL_DATABASE: mvc_hibernate
        ports:
          - 3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval "10s"
          --health-timeout "5s"
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'maven'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        #run: mvn -B clean install


      - name: Set up MySQL
        run: |
          # Команды для установки и запуска MySQL на локальной машине (не в Docker)
          # Для продакшена и тестирования на сервере:
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql  

      - name: Run tests
        run: mvn test
